services:
    kitchen:
        build:
            context: .
        volumes:
            - .:/var/www
        expose:
            - "9000"
        networks:
            - microservices-network

networks:
    microservices-network:
        external: true
